### PR TITLE
Create postcss.config.js

### PR DESCRIPTION
**Pull request by nadavshatz**
This is missing and breaks some builds.

### CODE REVIEW

**Comment by coderdiaz** [comment]
Can you share with me the cases?

**Comment by coderdiaz** [comment]
:shipit:

**Comment by nadavshatz** [comment]
@coderdiaz We're using postcss in our builds and when creating a production build it would fail with the following:

```
ERROR in ../node_modules/vue-status-indicator/styles.css
Module build failed: ModuleBuildError: Module build failed: Error: No PostCSS Config found in: /usr/src/node_modules/vue-status-indicator
    at config.load.then (/usr/src/node_modules/postcss-load-config/src/index.js:55:15)
    at runLoaders (/usr/src/node_modules/webpack/lib/NormalModule.js:195:19)
    at /usr/src/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /usr/src/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/usr/src/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Promise.resolve.then.then.catch (/usr/src/node_modules/postcss-loader/lib/index.js:194:71)
```

After adding the file it was all resolved.
do you mind releasing a new version so we can switch back to your fork from ours?

Thanks for merging!

**Comment by coderdiaz** [comment]
New release available `1.1.1` 🔥

**Pull request merged**
